### ISSUE TITLE
Support a CI

### ISSUE THREAD

**Issue by Swatto** [ChMat/ExcelBundle#1]
Since this code will evolve with your modifications and pull request, you should have a CI service that will ensure that there's no regression.

You have services (with Github integration) like:
- [Travis CI](travis-ci.org)
- [Circle CI](circleci.com)
- [PHPTesting](https://www.phptesting.org/) (self-hosted)

**Comment by ChMat** [comment]
Sure thing!

PHPUnit tests are already included for the features available at the moment. I'm satisfied with this for my personal usage, but I will surely try and extend testing if PR's are submitted.

Cheers,

Christian
